"""
Agent C - The Care Coordinator (Chat & Empathy Agent)
Maintains session state and guides patient based on agent findings
Provides empathetic, patient-friendly interaction and education

Enhanced with A2A Protocol for agent communication
"""

import time
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from patient_knowledge_graph import (
    PatientKnowledgeGraph,
    AgentAnalysis
)
from a2a_protocol import get_a2a_protocol, MessageType, MessagePriority, Message


class CareCoordinatorAgent:
    """
    Empathetic chat-focused agent that:
    - Maintains patient conversation history
    - Synthesizes findings from Analyzer and Pharmacist
    - Provides patient-friendly guidance and education
    - Tracks engagement and follow-up compliance
    
    Enhanced with A2A Protocol for communication with other agents
    """
    
    def __init__(self, knowledge_graph: PatientKnowledgeGraph):
        self.kg = knowledge_graph
        self.agent_name = "care_coordinator"
        self.session_active = False
        self.patient_context_understood = False
        
        # A2A Protocol Integration
        self.a2a_protocol = get_a2a_protocol()
        self.a2a_protocol.register_agent(self.agent_name)
    
    def initiate_patient_engagement(self) -> Tuple[str, AgentAnalysis]:
        """
        Start patient engagement session
        Introduces self and assesses patient understanding
        """
        start_time = time.time()
        analysis = AgentAnalysis(
            agent_name=self.agent_name,
            timestamp=datetime.now().isoformat(),
            status="processing"
        )
        
        try:
            self.session_active = True
            
            # Build welcome message based on available data
            discharge = self.kg.get_discharge_summary()
            
            if discharge:
                message = self._build_personalized_greeting(discharge)
            else:
                message = self._build_generic_greeting()
            
            analysis.findings = {
                "session_started": True,
                "patient_engaged": True,
                "context_status": "initializing"
            }
            
            analysis.reasoning = "Patient engagement session initiated. Waiting for patient input to understand their primary concerns and questions."
            
            analysis.recommendations = [
                "Assess patient understanding of discharge diagnosis",
                "Review medication management concerns",
                "Identify priority follow-up needs",
                "Provide emotional support and encouragement"
            ]
            
            analysis.status = "completed"
            
        except Exception as e:
            analysis.status = "error"
            analysis.error_message = str(e)
            message = "I apologize, but I encountered an issue. Please try again."
        
        analysis.execution_time_seconds = time.time() - start_time
        self.kg.add_agent_analysis(self.agent_name, analysis)
        
        return message, analysis
    
    def respond_to_patient_question(self, patient_message: str) -> Tuple[str, AgentAnalysis]:
        """
        Process patient question and provide empathetic, informed response
        Integrates findings from all agents
        """
        start_time = time.time()
        analysis = AgentAnalysis(
            agent_name=self.agent_name,
            timestamp=datetime.now().isoformat(),
            status="processing"
        )
        
        try:
            # Classify patient concern
            concern_type = self._classify_concern(patient_message)
            
            # Get response template
            response = self._generate_response(patient_message, concern_type)
            
            # Enhance with agent findings
            response = self._integrate_agent_findings(response, concern_type)
            
            # Add appropriate resources/next steps
            response = self._add_resources_and_guidance(response, concern_type)
            
            analysis.findings = {
                "concern_type": concern_type,
                "response_generated": True,
                "agents_consulted": ["analyzer", "pharmacist"]
            }
            
            analysis.reasoning = f"Patient inquired about {concern_type}. Response generated by integrating clinical data from Analyzer (patient info/diagnosis) and Pharmacist (medication/interaction data)."
            
            analysis.recommendations = [
                f"Monitor patient adherence to {concern_type}-related guidance",
                "Follow up on outstanding patient questions",
                "Schedule professional follow-up if additional guidance needed"
            ]
            
            analysis.status = "completed"
            
            # Store conversation
            self.kg.add_conversation(patient_message, response, self.agent_name)
            
            # A2A Protocol: Notify other agents about patient engagement
            engagement_data = {
                "action": "log_engagement",
                "concern_type": concern_type,
                "patient_responded": True,
                "session_active": True
            }
            
            self.a2a_protocol.broadcast_message(
                sender=self.agent_name,
                topic="patient_engagement",
                data=engagement_data,
                priority=MessagePriority.NORMAL
            )
            
        except Exception as e:
            analysis.status = "error"
            analysis.error_message = str(e)
            response = "I apologize for the difficulty. Please rephrase your question or contact your healthcare provider."
        
        analysis.execution_time_seconds = time.time() - start_time
        self.kg.add_agent_analysis(self.agent_name, analysis)
        
        return response, analysis
    
    def _build_personalized_greeting(self, discharge) -> str:
        """Build personalized greeting based on discharge data"""
        greeting = f"""
        👋 **Welcome, {discharge.patient_name}!**
        
        I'm your **MediSync Care Coordinator** - your personal health companion during your recovery.
        
        I see you were recently discharged for **{discharge.primary_diagnosis}** on **{discharge.discharge_date}**.
        
        **Here's how I can help you:**
        - 💊 Clarify your medications and how to take them
        - 🏥 Remind you of follow-up appointments
        - 🤔 Answer your recovery questions
        - 📋 Help you understand your discharge instructions
        - 📞 Connect you with resources when needed
        
        **What would you like to know first?** Feel free to ask about:
        - Your medications and side effects
        - Recovery timeline and activity limits
        - Warning signs to watch for
        - Upcoming appointments
        - Anything about your condition
        
        *I'm here to support your recovery! 💙*
        """
        return greeting.strip()
    
    def _build_generic_greeting(self) -> str:
        """Build generic greeting when no discharge data available"""
        greeting = """
        👋 **Welcome to MediSync Care Coordinator!**
        
        I'm your personal health companion, here to help you navigate your recovery and answer your health questions.
        
        **To get started, please help me understand your situation:**
        - What was your recent diagnosis or reason for hospital visit?
        - When were you discharged?
        - What medications are you currently taking?
        - Do you have any upcoming appointments scheduled?
        
        The more I know about your situation, the better I can support your recovery! 💙
        
        *What brings you here today?*
        """
        return greeting.strip()
    
    def _classify_concern(self, message: str) -> str:
        """Classify patient concern type"""
        message_lower = message.lower()
        
        if any(word in message_lower for word in ["medication", "pill", "dose", "medicine", "take"]):
            return "medications"
        elif any(word in message_lower for word in ["appointment", "follow", "doctor", "visit"]):
            return "appointments"
        elif any(word in message_lower for word in ["symptom", "pain", "fever", "bleeding", "shortness"]):
            return "symptoms"
        elif any(word in message_lower for word in ["diet", "eat", "food", "drink", "sodium"]):
            return "diet_nutrition"
        elif any(word in message_lower for word in ["activity", "exercise", "work", "drive", "lift"]):
            return "activity_restrictions"
        elif any(word in message_lower for word in ["recover", "heal", "timeline", "when", "how long"]):
            return "recovery_timeline"
        elif any(word in message_lower for word in ["side effect", "adverse", "reaction", "problem"]):
            return "side_effects"
        else:
            return "general_inquiry"
    
    def _generate_response(self, message: str, concern_type: str) -> str:
        """Generate empathetic, clinically appropriate response"""
        
        responses = {
            "medications": self._respond_to_medications,
            "appointments": self._respond_to_appointments,
            "symptoms": self._respond_to_symptoms,
            "diet_nutrition": self._respond_to_diet,
            "activity_restrictions": self._respond_to_activity,
            "recovery_timeline": self._respond_to_recovery,
            "side_effects": self._respond_to_side_effects,
            "general_inquiry": self._respond_to_general
        }
        
        response_generator = responses.get(concern_type, self._respond_to_general)
        return response_generator(message)
    
    def _respond_to_medications(self, message: str) -> str:
        """Generate medication-focused response"""
        medications = self.kg.get_current_medications()
        
        response = "**Medication Information**\n\n"
        
        if medications:
            response += "Here are your current medications:\n\n"
            for i, med in enumerate(medications, 1):
                response += f"{i}. **{med.name}** {med.dosage}\n"
                response += f"   - How often: {med.frequency}\n"
                response += f"   - How to take: {med.route}\n"
                response += f"   - Why: {med.indication}\n\n"
            
            response += "**Important Tips:**\n"
            response += "- ✅ Take medications exactly as prescribed\n"
            response += "- ✅ Set phone reminders for medication times\n"
            response += "- ✅ Don't skip doses even if you feel better\n"
            response += "- ✅ Let your doctor know about any side effects\n"
            response += "- ✅ Keep medications in original bottles\n"
            response += "- ✅ Don't share medications with others\n"
        else:
            response += "I don't have your medication list yet. Please ask your healthcare provider for a complete list.\n"
        
        response += "\n**Have any specific questions about a particular medication?**"
        return response
    
    def _respond_to_appointments(self, message: str) -> str:
        """Generate appointment-focused response"""
        follow_ups = self.kg.get_pending_follow_ups()
        
        response = "**Your Follow-up Appointments**\n\n"
        
        if follow_ups:
            response += "Here are your upcoming appointments:\n\n"
            for i, task in enumerate(follow_ups, 1):
                response += f"{i}. **{task.specialty or 'Medical'}** Appointment\n"
                response += f"   - Reason: {task.description}\n"
                response += f"   - Date: {task.scheduled_date or 'To be scheduled'}\n"
                response += f"   - Priority: {task.priority}\n\n"
            
            response += "**Before Each Appointment:**\n"
            response += "- 📋 Write down your questions and symptoms\n"
            response += "- 💊 Bring your medication list\n"
            response += "- 📱 Bring your insurance card\n"
            response += "- 🕐 Arrive 15 minutes early\n"
            response += "- 📸 Bring any test results or records\n"
        else:
            response += "No follow-up appointments are currently scheduled.\n"
            response += "**❗ Important:** Make sure you schedule appointments with your healthcare providers!\n"
        
        response += "\n**Questions about scheduling or preparing for appointments?**"
        return response
    
    def _respond_to_symptoms(self, message: str) -> str:
        """Generate symptom-focused response"""
        discharge = self.kg.get_discharge_summary()
        
        response = "**Understanding Your Symptoms**\n\n"
        
        response += "⚠️ **IMPORTANT:** If you experience any of these symptoms, **CALL 911 IMMEDIATELY**:\n"
        response += "- 🔴 Chest pain or pressure\n"
        response += "- 🔴 Severe shortness of breath\n"
        response += "- 🔴 Loss of consciousness\n"
        response += "- 🔴 Severe bleeding\n"
        response += "- 🔴 Signs of stroke (face drooping, arm weakness, slurred speech)\n\n"
        
        response += "**Contact Your Doctor If:**\n"
        response += "- 🟡 Symptoms are getting worse\n"
        response += "- 🟡 New symptoms develop\n"
        response += "- 🟡 Symptoms don't improve as expected\n"
        response += "- 🟡 Side effects from medications\n\n"
        
        if discharge:
            response += f"**Based on your {discharge.primary_diagnosis} diagnosis:**\n"
            response += "- Monitor for changes related to your condition\n"
            response += "- Keep track of your symptoms\n"
            response += "- Report patterns to your doctor\n"
        
        response += "\n**Can you tell me more about the symptoms you're experiencing?**"
        return response
    
    def _respond_to_diet(self, message: str) -> str:
        """Generate diet and nutrition response"""
        discharge = self.kg.get_discharge_summary()
        
        response = "**Diet and Nutrition Guidance**\n\n"
        
        if discharge and discharge.precautions:
            response += "**Your Discharge Precautions:**\n"
            for precaution in discharge.precautions:
                response += f"- {precaution}\n"
            response += "\n"
        
        response += "**General Post-Discharge Nutrition Tips:**\n"
        response += "- 🥗 Eat a balanced diet with fruits and vegetables\n"
        response += "- 💧 Stay well-hydrated - drink plenty of water\n"
        response += "- 🍞 Include fiber-rich foods for digestive health\n"
        response += "- 🧂 Follow any sodium, sugar, or dietary restrictions\n"
        response += "- ❌ Avoid excessive caffeine and alcohol\n"
        response += "- 🥛 Ask your doctor about specific dietary needs\n\n"
        
        response += "**Specific Questions About:**\n"
        response += "- Foods to avoid?\n"
        response += "- Dietary restrictions?\n"
        response += "- Fluid intake limits?\n"
        response += "- Meal planning ideas?\n"
        
        return response
    
    def _respond_to_activity(self, message: str) -> str:
        """Generate activity and exercise response"""
        discharge = self.kg.get_discharge_summary()
        
        response = "**Activity and Recovery Guidelines**\n\n"
        
        response += "**Return to Activities - General Timeline:**\n"
        response += "- 📺 Light activities (reading, watching TV): Immediately\n"
        response += "- 🚶 Light walking: Within days\n"
        response += "- 🏃 Moderate activities: 1-2 weeks (consult doctor)\n"
        response += "- 💪 Heavy lifting/exercise: 4-6 weeks (with approval)\n"
        response += "- 🏋️ Return to full activities: Per physician guidance\n\n"
        
        response += "**Important Precautions:**\n"
        response += "- Don't rush - let your body heal\n"
        response += "- Stop if you experience pain or shortness of breath\n"
        response += "- Get doctor's clearance before vigorous exercise\n"
        response += "- Gradually increase activity levels\n"
        response += "- Listen to your body's signals\n\n"
        
        if discharge and discharge.precautions:
            response += "**Your Specific Restrictions:**\n"
            for precaution in discharge.precautions:
                if any(word in precaution.lower() for word in ["activity", "exercise", "lift", "work", "drive"]):
                    response += f"- {precaution}\n"
        
        response += "\n**What activities are you interested in resuming?**"
        return response
    
    def _respond_to_recovery(self, message: str) -> str:
        """Generate recovery timeline response"""
        discharge = self.kg.get_discharge_summary()
        
        response = "**Recovery Timeline & Expectations**\n\n"
        
        if discharge:
            response += f"**Your Condition:** {discharge.primary_diagnosis}\n\n"
        
        response += "**Typical Recovery Phases:**\n"
        response += "- **Week 1-2:** Rest and pain management phase\n"
        response += "- **Week 2-4:** Gradual activity increase\n"
        response += "- **Week 4-8:** Progressive functional recovery\n"
        response += "- **Week 8+:** Return to baseline activities\n\n"
        
        response += "**What to Expect During Recovery:**\n"
        response += "- Gradual improvement - not linear\n"
        response += "- Some good days and challenging days\n"
        response += "- Fatigue is normal\n"
        response += "- Small setbacks can occur\n"
        response += "- Full recovery takes time and patience\n\n"
        
        response += "**Recovery Success Tips:**\n"
        response += "- ✅ Follow all medications as prescribed\n"
        response += "- ✅ Attend all follow-up appointments\n"
        response += "- ✅ Rest when needed\n"
        response += "- ✅ Communicate with your medical team\n"
        response += "- ✅ Stay positive and patient\n"
        response += "- ✅ Engage support system (family/friends)\n\n"
        
        response += "**Remember:** Everyone recovers at their own pace. Be patient with yourself! 💙"
        return response
    
    def _respond_to_side_effects(self, message: str) -> str:
        """Generate side effects response"""
        interactions = self.kg.drug_interactions
        
        response = "**Managing Medication Side Effects**\n\n"
        
        response += "**Common Side Effects (Usually Mild):**\n"
        response += "- Nausea: Take with food or ginger tea\n"
        response += "- Headache: Stay hydrated, over-the-counter pain relief\n"
        response += "- Dizziness: Get up slowly, avoid rapid movements\n"
        response += "- Constipation: Increase fiber and water intake\n"
        response += "- Sleep changes: Take medications at different times\n\n"
        
        response += "**⚠️ Serious Side Effects - Contact Doctor Immediately:**\n"
        response += "- Severe allergic reaction (rash, swelling, breathing difficulty)\n"
        response += "- Persistent severe headache or chest pain\n"
        response += "- Unusual bruising or bleeding\n"
        response += "- Severe stomach pain\n"
        response += "- Mental status changes\n\n"
        
        if interactions:
            critical = [i for i in interactions if i.severity.value == "critical"]
            major = [i for i in interactions if i.severity.value == "major"]
            
            if critical or major:
                response += "**Known Interactions with Your Medications:**\n"
                if critical:
                    response += f"🔴 {len(critical)} CRITICAL interaction(s) detected\n"
                if major:
                    response += f"🟡 {len(major)} MAJOR interaction(s) detected\n"
                response += "Contact your doctor or pharmacist immediately.\n\n"
        
        response += "**✅ Action Steps:**\n"
        response += "1. Write down all side effects\n"
        response += "2. Note when they occur\n"
        response += "3. Contact pharmacist or doctor\n"
        response += "4. Never stop medication without guidance\n"
        response += "5. Ask about alternative medications if needed\n"
        
        return response
    
    def _respond_to_general(self, message: str) -> str:
        """Generate general response"""
        response = "Thank you for reaching out! 💙\n\n"
        response += "I'm here to help with:\n"
        response += "- 💊 **Medications:** Questions about taking your medications\n"
        response += "- 🏥 **Appointments:** Information about follow-up visits\n"
        response += "- 🤒 **Symptoms:** Understanding what to expect during recovery\n"
        response += "- 🍎 **Diet:** Nutrition guidance for your condition\n"
        response += "- 🏃 **Activity:** What you can do as you recover\n"
        response += "- ⏰ **Timeline:** Expectations for your recovery\n"
        response += "- ⚠️ **Side Effects:** Managing medication reactions\n\n"
        response += "**What specific area would you like to know more about?**"
        
        return response
    
    def _integrate_agent_findings(self, response: str, concern_type: str) -> str:
        """Enhance response with findings from analyzer and pharmacist"""
        
        # Add relevant warnings from pharmacist if medication-related
        if concern_type == "medications":
            critical = self.kg.get_critical_interactions()
            if critical:
                response += f"\n\n🚨 **Important Safety Alert:**\n"
                response += f"Your pharmacist has flagged **{len(critical)}** critical medication interaction(s).\n"
                response += "**Please contact your doctor or pharmacist immediately before taking these medications together.**"
        
        # Add allergy information if relevant
        allergies = self.kg.get_allergies()
        if allergies and "medication" in concern_type:
            response += f"\n\n📋 **Your Allergies on File:**\n"
            for allergy in allergies:
                response += f"- {allergy}\n"
            response += "Always inform healthcare providers of these allergies."
        
        return response
    
    def _add_resources_and_guidance(self, response: str, concern_type: str) -> str:
        """Add helpful resources and next steps"""
        resources = f"\n\n---\n**Next Steps:**\n"
        
        if concern_type == "medications":
            resources += "💬 Keep your pharmacist's number handy\n"
            resources += "📱 Use a medication reminder app\n"
            resources += "📋 Maintain an updated medication list\n"
        elif concern_type == "symptoms":
            resources += "📞 Know when to call your doctor\n"
            resources += "🚨 Keep emergency numbers visible\n"
            resources += "📝 Keep a symptom diary\n"
        elif concern_type == "appointments":
            resources += "📅 Mark appointments on your calendar\n"
            resources += "📞 Confirm appointments 48 hours ahead\n"
            resources += "📸 Bring relevant medical records\n"
        
        resources += "\n**Questions? I'm always here to help!** 💙"
        
        return response + resources
    
    def generate_session_summary(self) -> str:
        """Generate summary of care coordinator session"""
        summary = "**MediSync Care Coordinator - Session Summary**\n\n"
        
        discharge = self.kg.get_discharge_summary()
        if discharge:
            summary += f"Patient: {discharge.patient_name} ({discharge.patient_id})\n"
            summary += f"Diagnosis: {discharge.primary_diagnosis}\n"
            summary += f"Discharge Date: {discharge.discharge_date}\n\n"
        
        medications = self.kg.get_current_medications()
        summary += f"Medications Managed: {len(medications)}\n"
        
        follow_ups = self.kg.get_pending_follow_ups()
        summary += f"Pending Follow-ups: {len(follow_ups)}\n"
        
        conversations = self.kg.get_conversation_history(limit=100)
        summary += f"Conversations: {len(conversations)} interactions\n"
        
        return summary
